<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Platforms>x64</Platforms>
        <!-- Needed for calling Rust functions. -->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Copy the Rust library to the RustLibrary subfolder of the solution folder.
    If no other changes have been made, rebuild to make this happen. -->
    <!-- Commenting this out because I have not been able to work out how to make
    it vary by operating system. -->
<!--    <Target Name="Update Rust Library" BeforeTargets="Compile">-->
<!--        <Exec Command="copy ..\..\Rust\millisecond_ticker\target\release\millisecond_ticker.dll; ..\RustLibrary /y"/>-->
<!--    </Target>-->

</Project>
